function augmenter = augmentData(type)
    % Define different augmentation strategies
    switch type
        case "exp1"
            augmenter = imageDataAugmenter( ...
                "RandRotation", [-45 45], ...
                "RandXReflection", true, ...
                "RandYReflection", true, ...
                "RandScale", [0.9 1.1]);

        case "exp2_3"
            augmenter = imageDataAugmenter( ...
                'RandRotation', [-20 20], ...
                'RandXShear', [-0.2 0.2], ...
                'RandYShear', [-0.2 0.2], ...
                'RandScale', [0.8 1.2], ...
                'RandXTranslation', [-20 20], ...
                'RandYTranslation', [-20 20], ...
                'RandXReflection', true, ...
                'FillValue', 0);
    end
end
